backend:
  name: github
  repo: anaechar/anaecha-nextjs-netlifycms
  branch: main
  base_url: https://anaecha.com
  auth_endpoint: api/auth
media_library:
  name: cloudinary
  config:
    cloud_name: "beforeifly"
    api_key: "822585855683452"
collections:
  - name: "posts"
    label: "Posts"
    folder: "contents/posts"
    extension: “mdx”
    format: “frontmatter”
    create: true
    view_filters:
      - label: "Drafts"
        field: "draft"
        pattern: true
    slug: "{{fields.slug}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", format: "D MMM YYYY",required: true}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "settings"
        file: "categories"
        search_fields: ["categories.*.name"]
        display_fields: ['categories.*.name']
        value_field: "categories.*.name"
        multiple: true
        required: true
      - {label: "Body", name: "body", widget: "markdown", required: true}