backend:
  name: github
  repo: anaechar/anaecha-nextjs-netlifycms
  branch: main
  base_url: https://anaecha.com
  auth_endpoint: api/auth
media_library:
  name: cloudinary
  config:
    cloud_name: "beforeifly"
    api_key: "822585855683452"
collections:
  - label: "Posts"
    name: "posts"
    folder: "contents/posts"
    extension: mdx
    format: frontmatter
    create: true
    view_filters:
      - label: "Drafts"
        field: "draft"
        pattern: true
    slug: "{{fields.slug}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", format: "D MMM YYYY",required: true}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "settings"
        file: "categories"
        search_fields: ["categories.*.name"]
        display_fields: ['categories.*.name']
        value_field: "categories.*.name"
        multiple: true
        required: true
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Robots", name: "robots", widget: "boolean", default: true}
  - label: "Pages"
    name: "pages"
    folder: "contents/pages"
    extension: mdx
    format: frontmatter
    create: true
    view_filters:
      - label: "Drafts"
        field: "draft"
        pattern: true
    slug: "{{fields.slug}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", format: "D MMM YYYY",required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Nav", name: "nav", widget: "boolean", default: false}
      - {label: "Robots", name: "robots", widget: "boolean", default: true}
  - label: "Settings"
    name: "settings"
    files: 
      - label: "Categories"
        name: "categories"
        file: "contents/posts-settings/categories.yml"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}